# Generated by Django 3.0.3 on 2020-02-11 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='live',
            name='starttime',
            field=models.DateTimeField(verbose_name='starttime'),
        ),
    ]
